#!/bin/bash

PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`

exec /usr/bin/java\
    -Xms512m\
    -Dapp.name="onyx"\
    -Dapp.pid="$$"\
    -Dapp.home="$BASEDIR" \
    -Dbasedir="$BASEDIR" \
    -jar /opt/onyx/onyx.jar
